services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - ./minecraft-data:/data
      - ./plugins:/plugins
    ports:
      - 19132:19132/udp
      - 25565:25565/tcp
    environment:
      PAPER_CHANNEL: "experimental"
      # CF_API_KEY: ${CF_API_KEY}
      # CURSEFORGE_FILES: |
      #   https://www.curseforge.com/minecraft/mc-mods/skinrestorer/files/5957054
      MOTD: "Aran8276 Cross Platform Paper Server"
      MAX_PLAYERS: 34
      ENABLE_AUTOPAUSE: "FALSE"
      PAUSE_WHEN_EMPTY_SECONDS: 86400
      MAX_TICK_TIME: -1
      EULA: "TRUE"
      TYPE: "PAPER"
      SPAWN_PROTECTION: "0"
      ONLINE_MODE: "FALSE"
      OPS: |
        aran8276
      CREATE_CONSOLE_IN_PIPE: "TRUE"
      tty: "TRUE"
      stdin_open: "TRUE"
      restart: unless-stopped
# volumes:
#   minecraftdata:
#     external: true
